#!/bin/sh /etc/rc.common

boot() {

	services=''

	for i in $services; do
		[ -x /etc/init.d/$i ] && /etc/init.d/$i boot 2>&1
	done

	# erase bootcounter and config
	cat /dev/zero > /dev/mtdblock-bootcfg 2>/dev/null
	flash_eraseall -j /dev/mtd-config 1>/dev/console 2>&1
	touch /var/first_boot
}
