#!/bin/sh /etc/rc.common

wait_networks() {
	while [ ! -e /var/state/networks ]; do
		sleep 1
	done
}

#
# this script is launched after nbd so now we can 
# launch the services which couldn't be launched in hotplug
#

updateNfo() {
    # gprs_device_state must be at available to start backup3g
    if [ -f /var/state/3gdongle ]; then
        status set gprs_device_state available
    fi
}

boot() {
	services='lighttpd dhcpd upnp igmp yaddns voip hotspot'
	coldplug='ushare samba p910nd backup3g'

	wait_networks
	updateNfo

	for i in $services $coldplug; do
		[ -x /etc/init.d/$i ] && /etc/init.d/$i boot 2>&1
	done

	touch /var/state/services
	event notify boot-succeeded
        
        # now, we can load usb-storage module to trigger hotplug scripts
        insmod usb-storage
}
